import { MaintenanceRequest, TabItem, Technician } from "@/types/request";

export const mockTechnicians: Technician[] = [
  {
    id: "TECH-001",
    name: "أحمد حسن",
    email: "ahmed.hassan@basma.com",
    specialization: "HVAC",
    status: "available",
    phone: "+966501234567",
  },
  {
    id: "TECH-002",
    name: "فاطمة علي",
    email: "fatima.ali@basma.com",
    specialization: "Electrical",
    status: "available",
    phone: "+966501234568",
  },
  {
    id: "TECH-003",
    name: "محمد إبراهيم",
    email: "mohammad.ibrahim@basma.com",
    specialization: "Plumbing",
    status: "busy",
    phone: "+966501234569",
  },
  {
    id: "TECH-004",
    name: "ليلى محمد",
    email: "layla.mohammed@basma.com",
    specialization: "Carpentry",
    status: "available",
    phone: "+966501234570",
  },
  {
    id: "TECH-005",
    name: "سمير خليل",
    email: "samir.khalil@basma.com",
    specialization: "General",
    status: "on-leave",
    phone: "+966501234571",
  },
  {
    id: "TECH-006",
    name: "نور حسن",
    email: "noor.hassan@basma.com",
    specialization: "HVAC",
    status: "available",
    phone: "+966501234572",
  },
];

export const mockRequests: MaintenanceRequest[] = [
  {
    id: "REQ-001",
    title: "مكيف الهواء لا يعمل",
    description:
      "وحدة التكييف في قاعة الاجتماعات لا تعمل بشكل صحيح. تبقى درجة الحرارة حوالي 28°م رغم ضبطها على 20°م.",
    location: "قاعة الاجتماعات - المبنى أ، الطابق الثالث",
    priority: "high",
    status: "pending",
    category: "HVAC",
    assignedTo: null,
    assignedToName: undefined,
    date: "2024-10-21",
    createdAt: "2024-10-21T09:00:00Z",
    updatedAt: "2024-10-21T09:00:00Z",
    createdBy: "user-001",
  },
  {
    id: "REQ-002",
    title: "أنبوب مياه مكسور",
    description:
      "تسرب مياه من تحت الحوض في الحمام. يحتاج إلى عناية فورية لمنع تلف المياه.",
    location: "الحمام - المبنى ب، الطابق الثاني",
    priority: "urgent",
    status: "assigned",
    category: "Plumbing",
    assignedTo: "TECH-003",
    assignedToName: "محمد إبراهيم",
    date: "2024-10-20",
    createdAt: "2024-10-20T14:30:00Z",
    updatedAt: "2024-10-21T08:15:00Z",
    createdBy: "user-002",
  },
  {
    id: "REQ-003",
    title: "مقبس كهربائي معطل",
    description:
      "المقبس الكهربائي في المكتب يشرق ولا يوفر طاقة ثابتة. خطر على السلامة.",
    location: "المكتب 305 - المبنى أ، الطابق الثالث",
    priority: "high",
    status: "in-progress",
    category: "Electrical",
    assignedTo: "TECH-002",
    assignedToName: "فاطمة علي",
    date: "2024-10-19",
    createdAt: "2024-10-19T11:20:00Z",
    updatedAt: "2024-10-21T10:45:00Z",
    createdBy: "user-001",
  },
  {
    id: "REQ-004",
    title: "قفل الباب معطل",
    description: "قفل الباب الرئيسي عالق ولا يستجيب لإدخال المفتاح.",
    location: "المدخل الرئيسي - المبنى أ، الطابق الأرضي",
    priority: "medium",
    status: "pending",
    category: "Carpentry",
    assignedTo: null,
    assignedToName: undefined,
    date: "2024-10-21",
    createdAt: "2024-10-21T07:30:00Z",
    updatedAt: "2024-10-21T07:30:00Z",
    createdBy: "user-003",
  },
  {
    id: "REQ-005",
    title: "تلف في السقف",
    description: "بقع مياه وتشققات في سقف غرفة التخزين. احتمال تسرب من الأعلى.",
    location: "غرفة التخزين - المبنى ج، الطابق الأول",
    priority: "medium",
    status: "assigned",
    category: "General",
    assignedTo: "TECH-001",
    assignedToName: "أحمد حسن",
    date: "2024-10-18",
    createdAt: "2024-10-18T13:15:00Z",
    updatedAt: "2024-10-20T16:00:00Z",
    createdBy: "user-002",
  },
  {
    id: "REQ-006",
    title: "فحص نظام التدفئة",
    description:
      "صيانة دورية لنظام التدفئة قبل الشتاء. يحتاج فحص المرشحات والترموستات.",
    location: "غرفة الميكانيكية - المبنى ب، الطابق السفلي",
    priority: "low",
    status: "completed",
    category: "HVAC",
    assignedTo: "TECH-001",
    assignedToName: "أحمد حسن",
    date: "2024-10-15",
    createdAt: "2024-10-15T10:00:00Z",
    updatedAt: "2024-10-21T09:30:00Z",
    createdBy: "user-001",
  },
  {
    id: "REQ-007",
    title: "تلف في طلاء الجدار",
    description:
      "الجدار في ممر المكتب يحتاج إعادة طلاء. خدوش واضحة وتلاشي اللون.",
    location: "ممر المكتب - المبنى أ، الطابق الثاني",
    priority: "low",
    status: "pending",
    category: "General",
    assignedTo: null,
    assignedToName: undefined,
    date: "2024-10-21",
    createdAt: "2024-10-21T08:00:00Z",
    updatedAt: "2024-10-21T08:00:00Z",
    createdBy: "user-004",
  },
  {
    id: "REQ-008",
    title: "استبدال المصابيح",
    description:
      "عدة مصابيح احترقت في اللوبي. يحتاج استبدال بمصابيح LED بديلة.",
    location: "اللوبي الرئيسي - المبنى أ، الطابق الأرضي",
    priority: "low",
    status: "in-progress",
    category: "Electrical",
    assignedTo: "TECH-002",
    assignedToName: "فاطمة علي",
    date: "2024-10-20",
    createdAt: "2024-10-20T09:15:00Z",
    updatedAt: "2024-10-21T11:00:00Z",
    createdBy: "user-001",
  },
  {
    id: "REQ-009",
    title: "باب الطوارئ",
    description: "إنذار باب الطوارئ لا يعمل. يحتاج اختبار وإصلاح نظام الإنذار.",
    location: "مخرج الطوارئ - المبنى ب، الطابق الثالث",
    priority: "urgent",
    status: "completed",
    category: "Electrical",
    assignedTo: "TECH-002",
    assignedToName: "فاطمة علي",
    date: "2024-10-17",
    createdAt: "2024-10-17T15:45:00Z",
    updatedAt: "2024-10-21T12:00:00Z",
    createdBy: "user-003",
  },
  {
    id: "REQ-010",
    title: "الثلاجة لا تعمل",
    description: "ثلاجة المكتب لا تبرد. درجة الحرارة ترتفع والطعام يفسد.",
    location: "غرفة الاستراحة - المبنى أ، الطابق الثاني",
    priority: "medium",
    status: "rejected",
    category: "General",
    assignedTo: null,
    assignedToName: undefined,
    date: "2024-10-21",
    createdAt: "2024-10-21T06:45:00Z",
    updatedAt: "2024-10-21T12:30:00Z",
    createdBy: "user-002",
  },
];

export const requestTabs: TabItem[] = [
  { id: "all", label: "All Requests" },
  { id: "pending", label: "Pending" },
  { id: "assigned", label: "Assigned" },
  { id: "in-progress", label: "In Progress" },
  { id: "completed", label: "Completed" },
  { id: "rejected", label: "Rejected" },
];
